// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSetXpByNameArgs {
    pub name: String,
    pub xp: u64,
}

impl From<AdminSetXpByNameArgs> for super::Reducer {
    fn from(args: AdminSetXpByNameArgs) -> Self {
        Self::AdminSetXpByName {
            name: args.name,
            xp: args.xp,
        }
    }
}

impl __sdk::InModule for AdminSetXpByNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_set_xp_by_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_set_xp_by_name {
    /// Request that the remote module invoke the reducer `admin_set_xp_by_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_set_xp_by_name:admin_set_xp_by_name_then`] to run a callback after the reducer completes.
    fn admin_set_xp_by_name(&self, name: String, xp: u64) -> __sdk::Result<()> {
        self.admin_set_xp_by_name_then(name, xp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_set_xp_by_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_set_xp_by_name_then(
        &self,
        name: String,
        xp: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_set_xp_by_name for super::RemoteReducers {
    fn admin_set_xp_by_name_then(
        &self,
        name: String,
        xp: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminSetXpByNameArgs { name, xp }, callback)
    }
}
