// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminPaintCellArgs {
    pub q: i32,
    pub r: i32,
}

impl From<AdminPaintCellArgs> for super::Reducer {
    fn from(args: AdminPaintCellArgs) -> Self {
        Self::AdminPaintCell {
            q: args.q,
            r: args.r,
        }
    }
}

impl __sdk::InModule for AdminPaintCellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_paint_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_paint_cell {
    /// Request that the remote module invoke the reducer `admin_paint_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_paint_cell:admin_paint_cell_then`] to run a callback after the reducer completes.
    fn admin_paint_cell(&self, q: i32, r: i32) -> __sdk::Result<()> {
        self.admin_paint_cell_then(q, r, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_paint_cell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_paint_cell_then(
        &self,
        q: i32,
        r: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_paint_cell for super::RemoteReducers {
    fn admin_paint_cell_then(
        &self,
        q: i32,
        r: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminPaintCellArgs { q, r }, callback)
    }
}
