// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateIslandArgs {
    pub island_id: u32,
    pub name: String,
    pub likes: u32,
    pub xp: u64,
}

impl From<AdminUpdateIslandArgs> for super::Reducer {
    fn from(args: AdminUpdateIslandArgs) -> Self {
        Self::AdminUpdateIsland {
            island_id: args.island_id,
            name: args.name,
            likes: args.likes,
            xp: args.xp,
        }
    }
}

impl __sdk::InModule for AdminUpdateIslandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_island`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_island {
    /// Request that the remote module invoke the reducer `admin_update_island` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_update_island:admin_update_island_then`] to run a callback after the reducer completes.
    fn admin_update_island(
        &self,
        island_id: u32,
        name: String,
        likes: u32,
        xp: u64,
    ) -> __sdk::Result<()> {
        self.admin_update_island_then(island_id, name, likes, xp, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_update_island` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_update_island_then(
        &self,
        island_id: u32,
        name: String,
        likes: u32,
        xp: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_update_island for super::RemoteReducers {
    fn admin_update_island_then(
        &self,
        island_id: u32,
        name: String,
        likes: u32,
        xp: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminUpdateIslandArgs {
                island_id,
                name,
                likes,
                xp,
            },
            callback,
        )
    }
}
