// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Cell {
    pub id: u32,
    pub col: u32,
    pub row: u32,
    pub color: u32,
    pub painted_by: __sdk::Identity,
    pub painted_at: __sdk::Timestamp,
}

impl __sdk::InModule for Cell {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Cell`.
///
/// Provides typed access to columns for query building.
pub struct CellCols {
    pub id: __sdk::__query_builder::Col<Cell, u32>,
    pub col: __sdk::__query_builder::Col<Cell, u32>,
    pub row: __sdk::__query_builder::Col<Cell, u32>,
    pub color: __sdk::__query_builder::Col<Cell, u32>,
    pub painted_by: __sdk::__query_builder::Col<Cell, __sdk::Identity>,
    pub painted_at: __sdk::__query_builder::Col<Cell, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Cell {
    type Cols = CellCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CellCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            col: __sdk::__query_builder::Col::new(table_name, "col"),
            row: __sdk::__query_builder::Col::new(table_name, "row"),
            color: __sdk::__query_builder::Col::new(table_name, "color"),
            painted_by: __sdk::__query_builder::Col::new(table_name, "painted_by"),
            painted_at: __sdk::__query_builder::Col::new(table_name, "painted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Cell`.
///
/// Provides typed access to indexed columns for query building.
pub struct CellIxCols {
    pub id: __sdk::__query_builder::IxCol<Cell, u32>,
}

impl __sdk::__query_builder::HasIxCols for Cell {
    type IxCols = CellIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CellIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Cell {}
