// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cell_type::Cell;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cell`.
///
/// Obtain a handle from the [`CellTableAccess::cell`] method on [`super::RemoteTables`],
/// like `ctx.db.cell()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell().on_insert(...)`.
pub struct CellTableHandle<'ctx> {
    imp: __sdk::TableHandle<Cell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cell`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CellTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CellTableHandle`], which mediates access to the table `cell`.
    fn cell(&self) -> CellTableHandle<'_>;
}

impl CellTableAccess for super::RemoteTables {
    fn cell(&self) -> CellTableHandle<'_> {
        CellTableHandle {
            imp: self.imp.get_table::<Cell>("cell"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CellInsertCallbackId(__sdk::CallbackId);
pub struct CellDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CellTableHandle<'ctx> {
    type Row = Cell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Cell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CellInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellInsertCallbackId {
        CellInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CellInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CellDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CellDeleteCallbackId {
        CellDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CellDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CellUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CellTableHandle<'ctx> {
    type UpdateCallbackId = CellUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CellUpdateCallbackId {
        CellUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CellUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `cell`,
/// which allows point queries on the field of the same name
/// via the [`CellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cell().id().find(...)`.
pub struct CellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Cell, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CellTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `cell`.
    pub fn id(&self) -> CellIdUnique<'ctx> {
        CellIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CellIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Cell> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Cell>("cell");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Cell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Cell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Cell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cellQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Cell`.
    fn cell(&self) -> __sdk::__query_builder::Table<Cell>;
}

impl cellQueryTableAccess for __sdk::QueryTableAccessor {
    fn cell(&self) -> __sdk::__query_builder::Table<Cell> {
        __sdk::__query_builder::Table::new("cell")
    }
}
