// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimGiftArgs {
    pub gift_id: u64,
}

impl From<ClaimGiftArgs> for super::Reducer {
    fn from(args: ClaimGiftArgs) -> Self {
        Self::ClaimGift {
            gift_id: args.gift_id,
        }
    }
}

impl __sdk::InModule for ClaimGiftArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_gift`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_gift {
    /// Request that the remote module invoke the reducer `claim_gift` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_gift:claim_gift_then`] to run a callback after the reducer completes.
    fn claim_gift(&self, gift_id: u64) -> __sdk::Result<()> {
        self.claim_gift_then(gift_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_gift` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_gift_then(
        &self,
        gift_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_gift for super::RemoteReducers {
    fn claim_gift_then(
        &self,
        gift_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClaimGiftArgs { gift_id }, callback)
    }
}
