// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimAdminArgs {
    pub password: String,
}

impl From<ClaimAdminArgs> for super::Reducer {
    fn from(args: ClaimAdminArgs) -> Self {
        Self::ClaimAdmin {
            password: args.password,
        }
    }
}

impl __sdk::InModule for ClaimAdminArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_admin`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_admin {
    /// Request that the remote module invoke the reducer `claim_admin` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_admin:claim_admin_then`] to run a callback after the reducer completes.
    fn claim_admin(&self, password: String) -> __sdk::Result<()> {
        self.claim_admin_then(password, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_admin` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_admin_then(
        &self,
        password: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_admin for super::RemoteReducers {
    fn claim_admin_then(
        &self,
        password: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClaimAdminArgs { password }, callback)
    }
}
