// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteAccountArgs {}

impl From<DeleteAccountArgs> for super::Reducer {
    fn from(args: DeleteAccountArgs) -> Self {
        Self::DeleteAccount
    }
}

impl __sdk::InModule for DeleteAccountArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_account {
    /// Request that the remote module invoke the reducer `delete_account` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_account:delete_account_then`] to run a callback after the reducer completes.
    fn delete_account(&self) -> __sdk::Result<()> {
        self.delete_account_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_account` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_account_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_account for super::RemoteReducers {
    fn delete_account_then(
        &self,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteAccountArgs {}, callback)
    }
}
