// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EraseCommunityCellArgs {
    pub q_local: i32,
    pub r_local: i32,
}

impl From<EraseCommunityCellArgs> for super::Reducer {
    fn from(args: EraseCommunityCellArgs) -> Self {
        Self::EraseCommunityCell {
            q_local: args.q_local,
            r_local: args.r_local,
        }
    }
}

impl __sdk::InModule for EraseCommunityCellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `erase_community_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait erase_community_cell {
    /// Request that the remote module invoke the reducer `erase_community_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`erase_community_cell:erase_community_cell_then`] to run a callback after the reducer completes.
    fn erase_community_cell(&self, q_local: i32, r_local: i32) -> __sdk::Result<()> {
        self.erase_community_cell_then(q_local, r_local, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `erase_community_cell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn erase_community_cell_then(
        &self,
        q_local: i32,
        r_local: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl erase_community_cell for super::RemoteReducers {
    fn erase_community_cell_then(
        &self,
        q_local: i32,
        r_local: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EraseCommunityCellArgs { q_local, r_local }, callback)
    }
}
