// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EraseMarginCellArgs {
    pub q: i32,
    pub r: i32,
}

impl From<EraseMarginCellArgs> for super::Reducer {
    fn from(args: EraseMarginCellArgs) -> Self {
        Self::EraseMarginCell {
            q: args.q,
            r: args.r,
        }
    }
}

impl __sdk::InModule for EraseMarginCellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `erase_margin_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait erase_margin_cell {
    /// Request that the remote module invoke the reducer `erase_margin_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`erase_margin_cell:erase_margin_cell_then`] to run a callback after the reducer completes.
    fn erase_margin_cell(&self, q: i32, r: i32) -> __sdk::Result<()> {
        self.erase_margin_cell_then(q, r, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `erase_margin_cell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn erase_margin_cell_then(
        &self,
        q: i32,
        r: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl erase_margin_cell for super::RemoteReducers {
    fn erase_margin_cell_then(
        &self,
        q: i32,
        r: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EraseMarginCellArgs { q, r }, callback)
    }
}
