// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gift_type::Gift;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gift`.
///
/// Obtain a handle from the [`GiftTableAccess::gift`] method on [`super::RemoteTables`],
/// like `ctx.db.gift()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gift().on_insert(...)`.
pub struct GiftTableHandle<'ctx> {
    imp: __sdk::TableHandle<Gift>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gift`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GiftTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GiftTableHandle`], which mediates access to the table `gift`.
    fn gift(&self) -> GiftTableHandle<'_>;
}

impl GiftTableAccess for super::RemoteTables {
    fn gift(&self) -> GiftTableHandle<'_> {
        GiftTableHandle {
            imp: self.imp.get_table::<Gift>("gift"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GiftInsertCallbackId(__sdk::CallbackId);
pub struct GiftDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GiftTableHandle<'ctx> {
    type Row = Gift;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Gift> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GiftInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GiftInsertCallbackId {
        GiftInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GiftInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GiftDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GiftDeleteCallbackId {
        GiftDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GiftDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GiftUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GiftTableHandle<'ctx> {
    type UpdateCallbackId = GiftUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GiftUpdateCallbackId {
        GiftUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GiftUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `gift`,
/// which allows point queries on the field of the same name
/// via the [`GiftIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gift().id().find(...)`.
pub struct GiftIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Gift, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GiftTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `gift`.
    pub fn id(&self) -> GiftIdUnique<'ctx> {
        GiftIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GiftIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Gift> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Gift>("gift");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Gift>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Gift>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Gift`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait giftQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Gift`.
    fn gift(&self) -> __sdk::__query_builder::Table<Gift>;
}

impl giftQueryTableAccess for __sdk::QueryTableAccessor {
    fn gift(&self) -> __sdk::__query_builder::Table<Gift> {
        __sdk::__query_builder::Table::new("gift")
    }
}
