// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Gift {
    pub id: u64,
    pub x: f32,
    pub y: f32,
    pub spawned_at: __sdk::Timestamp,
    pub expires_at: __sdk::Timestamp,
}

impl __sdk::InModule for Gift {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Gift`.
///
/// Provides typed access to columns for query building.
pub struct GiftCols {
    pub id: __sdk::__query_builder::Col<Gift, u64>,
    pub x: __sdk::__query_builder::Col<Gift, f32>,
    pub y: __sdk::__query_builder::Col<Gift, f32>,
    pub spawned_at: __sdk::__query_builder::Col<Gift, __sdk::Timestamp>,
    pub expires_at: __sdk::__query_builder::Col<Gift, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Gift {
    type Cols = GiftCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GiftCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            spawned_at: __sdk::__query_builder::Col::new(table_name, "spawned_at"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Gift`.
///
/// Provides typed access to indexed columns for query building.
pub struct GiftIxCols {
    pub id: __sdk::__query_builder::IxCol<Gift, u64>,
}

impl __sdk::__query_builder::HasIxCols for Gift {
    type IxCols = GiftIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GiftIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Gift {}
