// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hexa_cluster_type::HexaCluster;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hexa_cluster`.
///
/// Obtain a handle from the [`HexaClusterTableAccess::hexa_cluster`] method on [`super::RemoteTables`],
/// like `ctx.db.hexa_cluster()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hexa_cluster().on_insert(...)`.
pub struct HexaClusterTableHandle<'ctx> {
    imp: __sdk::TableHandle<HexaCluster>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hexa_cluster`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HexaClusterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HexaClusterTableHandle`], which mediates access to the table `hexa_cluster`.
    fn hexa_cluster(&self) -> HexaClusterTableHandle<'_>;
}

impl HexaClusterTableAccess for super::RemoteTables {
    fn hexa_cluster(&self) -> HexaClusterTableHandle<'_> {
        HexaClusterTableHandle {
            imp: self.imp.get_table::<HexaCluster>("hexa_cluster"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HexaClusterInsertCallbackId(__sdk::CallbackId);
pub struct HexaClusterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HexaClusterTableHandle<'ctx> {
    type Row = HexaCluster;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HexaCluster> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HexaClusterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HexaClusterInsertCallbackId {
        HexaClusterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HexaClusterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HexaClusterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HexaClusterDeleteCallbackId {
        HexaClusterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HexaClusterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HexaClusterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HexaClusterTableHandle<'ctx> {
    type UpdateCallbackId = HexaClusterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HexaClusterUpdateCallbackId {
        HexaClusterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HexaClusterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `hexa_cluster`,
/// which allows point queries on the field of the same name
/// via the [`HexaClusterIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hexa_cluster().identity().find(...)`.
pub struct HexaClusterIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HexaCluster, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HexaClusterTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `hexa_cluster`.
    pub fn identity(&self) -> HexaClusterIdentityUnique<'ctx> {
        HexaClusterIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HexaClusterIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<HexaCluster> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HexaCluster>("hexa_cluster");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HexaCluster>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HexaCluster>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HexaCluster`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hexa_clusterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HexaCluster`.
    fn hexa_cluster(&self) -> __sdk::__query_builder::Table<HexaCluster>;
}

impl hexa_clusterQueryTableAccess for __sdk::QueryTableAccessor {
    fn hexa_cluster(&self) -> __sdk::__query_builder::Table<HexaCluster> {
        __sdk::__query_builder::Table::new("hexa_cluster")
    }
}
