// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::hexa_event_type::HexaEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `hexa_event`.
///
/// Obtain a handle from the [`HexaEventTableAccess::hexa_event`] method on [`super::RemoteTables`],
/// like `ctx.db.hexa_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hexa_event().on_insert(...)`.
pub struct HexaEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<HexaEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `hexa_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait HexaEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`HexaEventTableHandle`], which mediates access to the table `hexa_event`.
    fn hexa_event(&self) -> HexaEventTableHandle<'_>;
}

impl HexaEventTableAccess for super::RemoteTables {
    fn hexa_event(&self) -> HexaEventTableHandle<'_> {
        HexaEventTableHandle {
            imp: self.imp.get_table::<HexaEvent>("hexa_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct HexaEventInsertCallbackId(__sdk::CallbackId);
pub struct HexaEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for HexaEventTableHandle<'ctx> {
    type Row = HexaEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = HexaEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = HexaEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HexaEventInsertCallbackId {
        HexaEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: HexaEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = HexaEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> HexaEventDeleteCallbackId {
        HexaEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: HexaEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct HexaEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for HexaEventTableHandle<'ctx> {
    type UpdateCallbackId = HexaEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> HexaEventUpdateCallbackId {
        HexaEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: HexaEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `hexa_event`,
/// which allows point queries on the field of the same name
/// via the [`HexaEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.hexa_event().id().find(...)`.
pub struct HexaEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<HexaEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> HexaEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `hexa_event`.
    pub fn id(&self) -> HexaEventIdUnique<'ctx> {
        HexaEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> HexaEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<HexaEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<HexaEvent>("hexa_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<HexaEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<HexaEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `HexaEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait hexa_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `HexaEvent`.
    fn hexa_event(&self) -> __sdk::__query_builder::Table<HexaEvent>;
}

impl hexa_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn hexa_event(&self) -> __sdk::__query_builder::Table<HexaEvent> {
        __sdk::__query_builder::Table::new("hexa_event")
    }
}
