// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HexaEvent {
    pub id: u64,
    pub at: __sdk::Timestamp,
    pub cx: f32,
    pub cy: f32,
    pub member_count: u32,
}

impl __sdk::InModule for HexaEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HexaEvent`.
///
/// Provides typed access to columns for query building.
pub struct HexaEventCols {
    pub id: __sdk::__query_builder::Col<HexaEvent, u64>,
    pub at: __sdk::__query_builder::Col<HexaEvent, __sdk::Timestamp>,
    pub cx: __sdk::__query_builder::Col<HexaEvent, f32>,
    pub cy: __sdk::__query_builder::Col<HexaEvent, f32>,
    pub member_count: __sdk::__query_builder::Col<HexaEvent, u32>,
}

impl __sdk::__query_builder::HasCols for HexaEvent {
    type Cols = HexaEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HexaEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cy: __sdk::__query_builder::Col::new(table_name, "cy"),
            member_count: __sdk::__query_builder::Col::new(table_name, "member_count"),
        }
    }
}

/// Indexed column accessor struct for the table `HexaEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct HexaEventIxCols {
    pub id: __sdk::__query_builder::IxCol<HexaEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for HexaEvent {
    type IxCols = HexaEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HexaEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HexaEvent {}
