// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HexaCluster {
    pub identity: __sdk::Identity,
    pub cluster_id: u64,
    pub cx: f32,
    pub cy: f32,
    pub member_count: u32,
    pub vertex_index: u32,
    pub ignited: bool,
}

impl __sdk::InModule for HexaCluster {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HexaCluster`.
///
/// Provides typed access to columns for query building.
pub struct HexaClusterCols {
    pub identity: __sdk::__query_builder::Col<HexaCluster, __sdk::Identity>,
    pub cluster_id: __sdk::__query_builder::Col<HexaCluster, u64>,
    pub cx: __sdk::__query_builder::Col<HexaCluster, f32>,
    pub cy: __sdk::__query_builder::Col<HexaCluster, f32>,
    pub member_count: __sdk::__query_builder::Col<HexaCluster, u32>,
    pub vertex_index: __sdk::__query_builder::Col<HexaCluster, u32>,
    pub ignited: __sdk::__query_builder::Col<HexaCluster, bool>,
}

impl __sdk::__query_builder::HasCols for HexaCluster {
    type Cols = HexaClusterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HexaClusterCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            cluster_id: __sdk::__query_builder::Col::new(table_name, "cluster_id"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cy: __sdk::__query_builder::Col::new(table_name, "cy"),
            member_count: __sdk::__query_builder::Col::new(table_name, "member_count"),
            vertex_index: __sdk::__query_builder::Col::new(table_name, "vertex_index"),
            ignited: __sdk::__query_builder::Col::new(table_name, "ignited"),
        }
    }
}

/// Indexed column accessor struct for the table `HexaCluster`.
///
/// Provides typed access to indexed columns for query building.
pub struct HexaClusterIxCols {
    pub identity: __sdk::__query_builder::IxCol<HexaCluster, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for HexaCluster {
    type IxCols = HexaClusterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HexaClusterIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HexaCluster {}
