// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Inventory {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub hue: u16,
    pub obtained_at: __sdk::Timestamp,
    pub obtained_with: Option<__sdk::Identity>,
    pub from_gift: bool,
}

impl __sdk::InModule for Inventory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Inventory`.
///
/// Provides typed access to columns for query building.
pub struct InventoryCols {
    pub id: __sdk::__query_builder::Col<Inventory, u64>,
    pub owner: __sdk::__query_builder::Col<Inventory, __sdk::Identity>,
    pub hue: __sdk::__query_builder::Col<Inventory, u16>,
    pub obtained_at: __sdk::__query_builder::Col<Inventory, __sdk::Timestamp>,
    pub obtained_with: __sdk::__query_builder::Col<Inventory, Option<__sdk::Identity>>,
    pub from_gift: __sdk::__query_builder::Col<Inventory, bool>,
}

impl __sdk::__query_builder::HasCols for Inventory {
    type Cols = InventoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            hue: __sdk::__query_builder::Col::new(table_name, "hue"),
            obtained_at: __sdk::__query_builder::Col::new(table_name, "obtained_at"),
            obtained_with: __sdk::__query_builder::Col::new(table_name, "obtained_with"),
            from_gift: __sdk::__query_builder::Col::new(table_name, "from_gift"),
        }
    }
}

/// Indexed column accessor struct for the table `Inventory`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryIxCols {
    pub id: __sdk::__query_builder::IxCol<Inventory, u64>,
    pub owner: __sdk::__query_builder::IxCol<Inventory, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Inventory {
    type IxCols = InventoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Inventory {}
