// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Island {
    pub id: u32,
    pub owner: __sdk::Identity,
    pub slot: u32,
    pub likes: u32,
    pub itch_rate_id: Option<u32>,
    pub created_at: __sdk::Timestamp,
    pub border_color: Option<u32>,
    pub border_hidden: bool,
}

impl __sdk::InModule for Island {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Island`.
///
/// Provides typed access to columns for query building.
pub struct IslandCols {
    pub id: __sdk::__query_builder::Col<Island, u32>,
    pub owner: __sdk::__query_builder::Col<Island, __sdk::Identity>,
    pub slot: __sdk::__query_builder::Col<Island, u32>,
    pub likes: __sdk::__query_builder::Col<Island, u32>,
    pub itch_rate_id: __sdk::__query_builder::Col<Island, Option<u32>>,
    pub created_at: __sdk::__query_builder::Col<Island, __sdk::Timestamp>,
    pub border_color: __sdk::__query_builder::Col<Island, Option<u32>>,
    pub border_hidden: __sdk::__query_builder::Col<Island, bool>,
}

impl __sdk::__query_builder::HasCols for Island {
    type Cols = IslandCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        IslandCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            likes: __sdk::__query_builder::Col::new(table_name, "likes"),
            itch_rate_id: __sdk::__query_builder::Col::new(table_name, "itch_rate_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            border_color: __sdk::__query_builder::Col::new(table_name, "border_color"),
            border_hidden: __sdk::__query_builder::Col::new(table_name, "border_hidden"),
        }
    }
}

/// Indexed column accessor struct for the table `Island`.
///
/// Provides typed access to indexed columns for query building.
pub struct IslandIxCols {
    pub id: __sdk::__query_builder::IxCol<Island, u32>,
    pub owner: __sdk::__query_builder::IxCol<Island, __sdk::Identity>,
    pub slot: __sdk::__query_builder::IxCol<Island, u32>,
}

impl __sdk::__query_builder::HasIxCols for Island {
    type IxCols = IslandIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        IslandIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            slot: __sdk::__query_builder::IxCol::new(table_name, "slot"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Island {}
