// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::island_like_type::IslandLike;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `island_like`.
///
/// Obtain a handle from the [`IslandLikeTableAccess::island_like`] method on [`super::RemoteTables`],
/// like `ctx.db.island_like()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_like().on_insert(...)`.
pub struct IslandLikeTableHandle<'ctx> {
    imp: __sdk::TableHandle<IslandLike>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `island_like`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IslandLikeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IslandLikeTableHandle`], which mediates access to the table `island_like`.
    fn island_like(&self) -> IslandLikeTableHandle<'_>;
}

impl IslandLikeTableAccess for super::RemoteTables {
    fn island_like(&self) -> IslandLikeTableHandle<'_> {
        IslandLikeTableHandle {
            imp: self.imp.get_table::<IslandLike>("island_like"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IslandLikeInsertCallbackId(__sdk::CallbackId);
pub struct IslandLikeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IslandLikeTableHandle<'ctx> {
    type Row = IslandLike;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = IslandLike> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IslandLikeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandLikeInsertCallbackId {
        IslandLikeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IslandLikeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IslandLikeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandLikeDeleteCallbackId {
        IslandLikeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IslandLikeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IslandLikeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IslandLikeTableHandle<'ctx> {
    type UpdateCallbackId = IslandLikeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IslandLikeUpdateCallbackId {
        IslandLikeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IslandLikeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `island_like`,
/// which allows point queries on the field of the same name
/// via the [`IslandLikeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_like().id().find(...)`.
pub struct IslandLikeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<IslandLike, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandLikeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `island_like`.
    pub fn id(&self) -> IslandLikeIdUnique<'ctx> {
        IslandLikeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandLikeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<IslandLike> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<IslandLike>("island_like");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<IslandLike>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<IslandLike>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `IslandLike`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait island_likeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `IslandLike`.
    fn island_like(&self) -> __sdk::__query_builder::Table<IslandLike>;
}

impl island_likeQueryTableAccess for __sdk::QueryTableAccessor {
    fn island_like(&self) -> __sdk::__query_builder::Table<IslandLike> {
        __sdk::__query_builder::Table::new("island_like")
    }
}
