// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::island_type::Island;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `island`.
///
/// Obtain a handle from the [`IslandTableAccess::island`] method on [`super::RemoteTables`],
/// like `ctx.db.island()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island().on_insert(...)`.
pub struct IslandTableHandle<'ctx> {
    imp: __sdk::TableHandle<Island>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `island`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IslandTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IslandTableHandle`], which mediates access to the table `island`.
    fn island(&self) -> IslandTableHandle<'_>;
}

impl IslandTableAccess for super::RemoteTables {
    fn island(&self) -> IslandTableHandle<'_> {
        IslandTableHandle {
            imp: self.imp.get_table::<Island>("island"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IslandInsertCallbackId(__sdk::CallbackId);
pub struct IslandDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IslandTableHandle<'ctx> {
    type Row = Island;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Island> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IslandInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandInsertCallbackId {
        IslandInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IslandInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IslandDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandDeleteCallbackId {
        IslandDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IslandDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IslandUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IslandTableHandle<'ctx> {
    type UpdateCallbackId = IslandUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IslandUpdateCallbackId {
        IslandUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IslandUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `island`,
/// which allows point queries on the field of the same name
/// via the [`IslandIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island().id().find(...)`.
pub struct IslandIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Island, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `island`.
    pub fn id(&self) -> IslandIdUnique<'ctx> {
        IslandIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Island> {
        self.imp.find(col_val)
    }
}

/// Access to the `owner` unique index on the table `island`,
/// which allows point queries on the field of the same name
/// via the [`IslandOwnerUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island().owner().find(...)`.
pub struct IslandOwnerUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Island, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandTableHandle<'ctx> {
    /// Get a handle on the `owner` unique index on the table `island`.
    pub fn owner(&self) -> IslandOwnerUnique<'ctx> {
        IslandOwnerUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("owner"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandOwnerUnique<'ctx> {
    /// Find the subscribed row whose `owner` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Island> {
        self.imp.find(col_val)
    }
}

/// Access to the `slot` unique index on the table `island`,
/// which allows point queries on the field of the same name
/// via the [`IslandSlotUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island().slot().find(...)`.
pub struct IslandSlotUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Island, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandTableHandle<'ctx> {
    /// Get a handle on the `slot` unique index on the table `island`.
    pub fn slot(&self) -> IslandSlotUnique<'ctx> {
        IslandSlotUnique {
            imp: self.imp.get_unique_constraint::<u32>("slot"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandSlotUnique<'ctx> {
    /// Find the subscribed row whose `slot` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Island> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Island>("island");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
    _table.add_unique_constraint::<__sdk::Identity>("owner", |row| &row.owner);
    _table.add_unique_constraint::<u32>("slot", |row| &row.slot);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Island>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Island>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Island`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait islandQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Island`.
    fn island(&self) -> __sdk::__query_builder::Table<Island>;
}

impl islandQueryTableAccess for __sdk::QueryTableAccessor {
    fn island(&self) -> __sdk::__query_builder::Table<Island> {
        __sdk::__query_builder::Table::new("island")
    }
}
