// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::island_link_click_type::IslandLinkClick;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `island_link_click`.
///
/// Obtain a handle from the [`IslandLinkClickTableAccess::island_link_click`] method on [`super::RemoteTables`],
/// like `ctx.db.island_link_click()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_link_click().on_insert(...)`.
pub struct IslandLinkClickTableHandle<'ctx> {
    imp: __sdk::TableHandle<IslandLinkClick>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `island_link_click`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IslandLinkClickTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IslandLinkClickTableHandle`], which mediates access to the table `island_link_click`.
    fn island_link_click(&self) -> IslandLinkClickTableHandle<'_>;
}

impl IslandLinkClickTableAccess for super::RemoteTables {
    fn island_link_click(&self) -> IslandLinkClickTableHandle<'_> {
        IslandLinkClickTableHandle {
            imp: self.imp.get_table::<IslandLinkClick>("island_link_click"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IslandLinkClickInsertCallbackId(__sdk::CallbackId);
pub struct IslandLinkClickDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IslandLinkClickTableHandle<'ctx> {
    type Row = IslandLinkClick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = IslandLinkClick> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IslandLinkClickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandLinkClickInsertCallbackId {
        IslandLinkClickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IslandLinkClickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IslandLinkClickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandLinkClickDeleteCallbackId {
        IslandLinkClickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IslandLinkClickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IslandLinkClickUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IslandLinkClickTableHandle<'ctx> {
    type UpdateCallbackId = IslandLinkClickUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IslandLinkClickUpdateCallbackId {
        IslandLinkClickUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IslandLinkClickUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `island_link_click`,
/// which allows point queries on the field of the same name
/// via the [`IslandLinkClickIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_link_click().id().find(...)`.
pub struct IslandLinkClickIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<IslandLinkClick, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandLinkClickTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `island_link_click`.
    pub fn id(&self) -> IslandLinkClickIdUnique<'ctx> {
        IslandLinkClickIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandLinkClickIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<IslandLinkClick> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<IslandLinkClick>("island_link_click");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<IslandLinkClick>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<IslandLinkClick>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `IslandLinkClick`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait island_link_clickQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `IslandLinkClick`.
    fn island_link_click(&self) -> __sdk::__query_builder::Table<IslandLinkClick>;
}

impl island_link_clickQueryTableAccess for __sdk::QueryTableAccessor {
    fn island_link_click(&self) -> __sdk::__query_builder::Table<IslandLinkClick> {
        __sdk::__query_builder::Table::new("island_link_click")
    }
}
