// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::island_cell_type::IslandCell;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `island_cell`.
///
/// Obtain a handle from the [`IslandCellTableAccess::island_cell`] method on [`super::RemoteTables`],
/// like `ctx.db.island_cell()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_cell().on_insert(...)`.
pub struct IslandCellTableHandle<'ctx> {
    imp: __sdk::TableHandle<IslandCell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `island_cell`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IslandCellTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IslandCellTableHandle`], which mediates access to the table `island_cell`.
    fn island_cell(&self) -> IslandCellTableHandle<'_>;
}

impl IslandCellTableAccess for super::RemoteTables {
    fn island_cell(&self) -> IslandCellTableHandle<'_> {
        IslandCellTableHandle {
            imp: self.imp.get_table::<IslandCell>("island_cell"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IslandCellInsertCallbackId(__sdk::CallbackId);
pub struct IslandCellDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IslandCellTableHandle<'ctx> {
    type Row = IslandCell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = IslandCell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IslandCellInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandCellInsertCallbackId {
        IslandCellInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IslandCellInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IslandCellDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IslandCellDeleteCallbackId {
        IslandCellDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IslandCellDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct IslandCellUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IslandCellTableHandle<'ctx> {
    type UpdateCallbackId = IslandCellUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IslandCellUpdateCallbackId {
        IslandCellUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IslandCellUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `island_cell`,
/// which allows point queries on the field of the same name
/// via the [`IslandCellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.island_cell().id().find(...)`.
pub struct IslandCellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<IslandCell, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IslandCellTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `island_cell`.
    pub fn id(&self) -> IslandCellIdUnique<'ctx> {
        IslandCellIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IslandCellIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<IslandCell> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<IslandCell>("island_cell");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<IslandCell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<IslandCell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `IslandCell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait island_cellQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `IslandCell`.
    fn island_cell(&self) -> __sdk::__query_builder::Table<IslandCell>;
}

impl island_cellQueryTableAccess for __sdk::QueryTableAccessor {
    fn island_cell(&self) -> __sdk::__query_builder::Table<IslandCell> {
        __sdk::__query_builder::Table::new("island_cell")
    }
}
