// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::margin_cell_type::MarginCell;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `margin_cell`.
///
/// Obtain a handle from the [`MarginCellTableAccess::margin_cell`] method on [`super::RemoteTables`],
/// like `ctx.db.margin_cell()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.margin_cell().on_insert(...)`.
pub struct MarginCellTableHandle<'ctx> {
    imp: __sdk::TableHandle<MarginCell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `margin_cell`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MarginCellTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MarginCellTableHandle`], which mediates access to the table `margin_cell`.
    fn margin_cell(&self) -> MarginCellTableHandle<'_>;
}

impl MarginCellTableAccess for super::RemoteTables {
    fn margin_cell(&self) -> MarginCellTableHandle<'_> {
        MarginCellTableHandle {
            imp: self.imp.get_table::<MarginCell>("margin_cell"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MarginCellInsertCallbackId(__sdk::CallbackId);
pub struct MarginCellDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MarginCellTableHandle<'ctx> {
    type Row = MarginCell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MarginCell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MarginCellInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarginCellInsertCallbackId {
        MarginCellInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MarginCellInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MarginCellDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MarginCellDeleteCallbackId {
        MarginCellDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MarginCellDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MarginCellUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MarginCellTableHandle<'ctx> {
    type UpdateCallbackId = MarginCellUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MarginCellUpdateCallbackId {
        MarginCellUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MarginCellUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `margin_cell`,
/// which allows point queries on the field of the same name
/// via the [`MarginCellIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.margin_cell().id().find(...)`.
pub struct MarginCellIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MarginCell, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MarginCellTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `margin_cell`.
    pub fn id(&self) -> MarginCellIdUnique<'ctx> {
        MarginCellIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MarginCellIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<MarginCell> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MarginCell>("margin_cell");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MarginCell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MarginCell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MarginCell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait margin_cellQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MarginCell`.
    fn margin_cell(&self) -> __sdk::__query_builder::Table<MarginCell>;
}

impl margin_cellQueryTableAccess for __sdk::QueryTableAccessor {
    fn margin_cell(&self) -> __sdk::__query_builder::Table<MarginCell> {
        __sdk::__query_builder::Table::new("margin_cell")
    }
}
