// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::merge_event_type::MergeEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `merge_event`.
///
/// Obtain a handle from the [`MergeEventTableAccess::merge_event`] method on [`super::RemoteTables`],
/// like `ctx.db.merge_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.merge_event().on_insert(...)`.
pub struct MergeEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<MergeEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `merge_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MergeEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MergeEventTableHandle`], which mediates access to the table `merge_event`.
    fn merge_event(&self) -> MergeEventTableHandle<'_>;
}

impl MergeEventTableAccess for super::RemoteTables {
    fn merge_event(&self) -> MergeEventTableHandle<'_> {
        MergeEventTableHandle {
            imp: self.imp.get_table::<MergeEvent>("merge_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MergeEventInsertCallbackId(__sdk::CallbackId);
pub struct MergeEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MergeEventTableHandle<'ctx> {
    type Row = MergeEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MergeEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MergeEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MergeEventInsertCallbackId {
        MergeEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MergeEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MergeEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MergeEventDeleteCallbackId {
        MergeEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MergeEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MergeEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MergeEventTableHandle<'ctx> {
    type UpdateCallbackId = MergeEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MergeEventUpdateCallbackId {
        MergeEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MergeEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `merge_event`,
/// which allows point queries on the field of the same name
/// via the [`MergeEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.merge_event().id().find(...)`.
pub struct MergeEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MergeEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MergeEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `merge_event`.
    pub fn id(&self) -> MergeEventIdUnique<'ctx> {
        MergeEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MergeEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MergeEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MergeEvent>("merge_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MergeEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MergeEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MergeEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait merge_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MergeEvent`.
    fn merge_event(&self) -> __sdk::__query_builder::Table<MergeEvent>;
}

impl merge_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn merge_event(&self) -> __sdk::__query_builder::Table<MergeEvent> {
        __sdk::__query_builder::Table::new("merge_event")
    }
}
