// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MergeEvent {
    pub id: u64,
    pub at: __sdk::Timestamp,
    pub a: __sdk::Identity,
    pub b: __sdk::Identity,
    pub hue_a: u16,
    pub hue_b: u16,
    pub merged_hue: u16,
    pub merged_sat: u8,
    pub merged_val: u8,
}

impl __sdk::InModule for MergeEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MergeEvent`.
///
/// Provides typed access to columns for query building.
pub struct MergeEventCols {
    pub id: __sdk::__query_builder::Col<MergeEvent, u64>,
    pub at: __sdk::__query_builder::Col<MergeEvent, __sdk::Timestamp>,
    pub a: __sdk::__query_builder::Col<MergeEvent, __sdk::Identity>,
    pub b: __sdk::__query_builder::Col<MergeEvent, __sdk::Identity>,
    pub hue_a: __sdk::__query_builder::Col<MergeEvent, u16>,
    pub hue_b: __sdk::__query_builder::Col<MergeEvent, u16>,
    pub merged_hue: __sdk::__query_builder::Col<MergeEvent, u16>,
    pub merged_sat: __sdk::__query_builder::Col<MergeEvent, u8>,
    pub merged_val: __sdk::__query_builder::Col<MergeEvent, u8>,
}

impl __sdk::__query_builder::HasCols for MergeEvent {
    type Cols = MergeEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MergeEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
            a: __sdk::__query_builder::Col::new(table_name, "a"),
            b: __sdk::__query_builder::Col::new(table_name, "b"),
            hue_a: __sdk::__query_builder::Col::new(table_name, "hue_a"),
            hue_b: __sdk::__query_builder::Col::new(table_name, "hue_b"),
            merged_hue: __sdk::__query_builder::Col::new(table_name, "merged_hue"),
            merged_sat: __sdk::__query_builder::Col::new(table_name, "merged_sat"),
            merged_val: __sdk::__query_builder::Col::new(table_name, "merged_val"),
        }
    }
}

/// Indexed column accessor struct for the table `MergeEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct MergeEventIxCols {
    pub id: __sdk::__query_builder::IxCol<MergeEvent, u64>,
}

impl __sdk::__query_builder::HasIxCols for MergeEvent {
    type IxCols = MergeEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MergeEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MergeEvent {}
