// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MergeWithCellArgs {
    pub cell_kind: u8,
    pub cell_id: u32,
}

impl From<MergeWithCellArgs> for super::Reducer {
    fn from(args: MergeWithCellArgs) -> Self {
        Self::MergeWithCell {
            cell_kind: args.cell_kind,
            cell_id: args.cell_id,
        }
    }
}

impl __sdk::InModule for MergeWithCellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `merge_with_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait merge_with_cell {
    /// Request that the remote module invoke the reducer `merge_with_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`merge_with_cell:merge_with_cell_then`] to run a callback after the reducer completes.
    fn merge_with_cell(&self, cell_kind: u8, cell_id: u32) -> __sdk::Result<()> {
        self.merge_with_cell_then(cell_kind, cell_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `merge_with_cell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn merge_with_cell_then(
        &self,
        cell_kind: u8,
        cell_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl merge_with_cell for super::RemoteReducers {
    fn merge_with_cell_then(
        &self,
        cell_kind: u8,
        cell_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MergeWithCellArgs { cell_kind, cell_id }, callback)
    }
}
