// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod claim_admin_reducer;
pub mod claim_gift_reducer;
pub mod click_link_reducer;
pub mod config_table;
pub mod config_type;
pub mod delete_island_cells_reducer;
pub mod disable_island_border_reducer;
pub mod erase_community_cell_reducer;
pub mod erase_island_cell_reducer;
pub mod erase_margin_cell_reducer;
pub mod gift_schedule_type;
pub mod gift_table;
pub mod gift_type;
pub mod hexa_cluster_table;
pub mod hexa_cluster_type;
pub mod hexa_event_table;
pub mod hexa_event_type;
pub mod hexa_reward_type;
pub mod hexa_sweep_schedule_type;
pub mod inventory_table;
pub mod inventory_type;
pub mod island_cell_table;
pub mod island_cell_type;
pub mod island_like_table;
pub mod island_like_type;
pub mod island_link_click_table;
pub mod island_link_click_type;
pub mod island_table;
pub mod island_type;
pub mod like_island_reducer;
pub mod margin_cell_table;
pub mod margin_cell_type;
pub mod merge_with_cell_reducer;
pub mod paint_community_cell_reducer;
pub mod paint_island_cell_reducer;
pub mod paint_margin_cell_reducer;
pub mod reap_schedule_type;
pub mod rerank_fire_schedule_type;
pub mod rerank_warn_schedule_type;
pub mod reset_account_reducer;
pub mod set_brush_reducer;
pub mod set_frozen_reducer;
pub mod set_island_border_reducer;
pub mod set_island_link_reducer;
pub mod set_lock_reducer;
pub mod set_name_reducer;
pub mod set_pos_reducer;
pub mod show_island_border_reducer;
pub mod time_xp_schedule_type;
pub mod unlike_island_reducer;
pub mod user_table;
pub mod user_type;

pub use claim_admin_reducer::claim_admin;
pub use claim_gift_reducer::claim_gift;
pub use click_link_reducer::click_link;
pub use config_table::*;
pub use config_type::Config;
pub use delete_island_cells_reducer::delete_island_cells;
pub use disable_island_border_reducer::disable_island_border;
pub use erase_community_cell_reducer::erase_community_cell;
pub use erase_island_cell_reducer::erase_island_cell;
pub use erase_margin_cell_reducer::erase_margin_cell;
pub use gift_schedule_type::GiftSchedule;
pub use gift_table::*;
pub use gift_type::Gift;
pub use hexa_cluster_table::*;
pub use hexa_cluster_type::HexaCluster;
pub use hexa_event_table::*;
pub use hexa_event_type::HexaEvent;
pub use hexa_reward_type::HexaReward;
pub use hexa_sweep_schedule_type::HexaSweepSchedule;
pub use inventory_table::*;
pub use inventory_type::Inventory;
pub use island_cell_table::*;
pub use island_cell_type::IslandCell;
pub use island_like_table::*;
pub use island_like_type::IslandLike;
pub use island_link_click_table::*;
pub use island_link_click_type::IslandLinkClick;
pub use island_table::*;
pub use island_type::Island;
pub use like_island_reducer::like_island;
pub use margin_cell_table::*;
pub use margin_cell_type::MarginCell;
pub use merge_with_cell_reducer::merge_with_cell;
pub use paint_community_cell_reducer::paint_community_cell;
pub use paint_island_cell_reducer::paint_island_cell;
pub use paint_margin_cell_reducer::paint_margin_cell;
pub use reap_schedule_type::ReapSchedule;
pub use rerank_fire_schedule_type::RerankFireSchedule;
pub use rerank_warn_schedule_type::RerankWarnSchedule;
pub use reset_account_reducer::reset_account;
pub use set_brush_reducer::set_brush;
pub use set_frozen_reducer::set_frozen;
pub use set_island_border_reducer::set_island_border;
pub use set_island_link_reducer::set_island_link;
pub use set_lock_reducer::set_lock;
pub use set_name_reducer::set_name;
pub use set_pos_reducer::set_pos;
pub use show_island_border_reducer::show_island_border;
pub use time_xp_schedule_type::TimeXpSchedule;
pub use unlike_island_reducer::unlike_island;
pub use user_table::*;
pub use user_type::User;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    ClaimAdmin { password: String },
    ClaimGift { gift_id: u64 },
    ClickLink { island_id: u32 },
    DeleteIslandCells { island_id: u32 },
    DisableIslandBorder,
    EraseCommunityCell { q_local: i32, r_local: i32 },
    EraseIslandCell { q_local: i32, r_local: i32 },
    EraseMarginCell { q: i32, r: i32 },
    LikeIsland { island_id: u32 },
    MergeWithCell { cell_kind: u8, cell_id: u32 },
    PaintCommunityCell { q_local: i32, r_local: i32 },
    PaintIslandCell { q_local: i32, r_local: i32 },
    PaintMarginCell { q: i32, r: i32 },
    ResetAccount,
    SetBrush { hue: u16, sat: u8, val: u8 },
    SetFrozen { frozen: bool },
    SetIslandBorder,
    SetIslandLink { rate_id: u32 },
    SetLock { locked: bool },
    SetName { name: String },
    SetPos { cx: f32, cy: f32 },
    ShowIslandBorder,
    UnlikeIsland { island_id: u32 },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::ClaimAdmin { .. } => "claim_admin",
            Reducer::ClaimGift { .. } => "claim_gift",
            Reducer::ClickLink { .. } => "click_link",
            Reducer::DeleteIslandCells { .. } => "delete_island_cells",
            Reducer::DisableIslandBorder => "disable_island_border",
            Reducer::EraseCommunityCell { .. } => "erase_community_cell",
            Reducer::EraseIslandCell { .. } => "erase_island_cell",
            Reducer::EraseMarginCell { .. } => "erase_margin_cell",
            Reducer::LikeIsland { .. } => "like_island",
            Reducer::MergeWithCell { .. } => "merge_with_cell",
            Reducer::PaintCommunityCell { .. } => "paint_community_cell",
            Reducer::PaintIslandCell { .. } => "paint_island_cell",
            Reducer::PaintMarginCell { .. } => "paint_margin_cell",
            Reducer::ResetAccount => "reset_account",
            Reducer::SetBrush { .. } => "set_brush",
            Reducer::SetFrozen { .. } => "set_frozen",
            Reducer::SetIslandBorder => "set_island_border",
            Reducer::SetIslandLink { .. } => "set_island_link",
            Reducer::SetLock { .. } => "set_lock",
            Reducer::SetName { .. } => "set_name",
            Reducer::SetPos { .. } => "set_pos",
            Reducer::ShowIslandBorder => "show_island_border",
            Reducer::UnlikeIsland { .. } => "unlike_island",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::ClaimAdmin { password } => {
                __sats::bsatn::to_vec(&claim_admin_reducer::ClaimAdminArgs {
                    password: password.clone(),
                })
            }
            Reducer::ClaimGift { gift_id } => {
                __sats::bsatn::to_vec(&claim_gift_reducer::ClaimGiftArgs {
                    gift_id: gift_id.clone(),
                })
            }
            Reducer::ClickLink { island_id } => {
                __sats::bsatn::to_vec(&click_link_reducer::ClickLinkArgs {
                    island_id: island_id.clone(),
                })
            }
            Reducer::DeleteIslandCells { island_id } => {
                __sats::bsatn::to_vec(&delete_island_cells_reducer::DeleteIslandCellsArgs {
                    island_id: island_id.clone(),
                })
            }
            Reducer::DisableIslandBorder => {
                __sats::bsatn::to_vec(&disable_island_border_reducer::DisableIslandBorderArgs {})
            }
            Reducer::EraseCommunityCell { q_local, r_local } => {
                __sats::bsatn::to_vec(&erase_community_cell_reducer::EraseCommunityCellArgs {
                    q_local: q_local.clone(),
                    r_local: r_local.clone(),
                })
            }
            Reducer::EraseIslandCell { q_local, r_local } => {
                __sats::bsatn::to_vec(&erase_island_cell_reducer::EraseIslandCellArgs {
                    q_local: q_local.clone(),
                    r_local: r_local.clone(),
                })
            }
            Reducer::EraseMarginCell { q, r } => {
                __sats::bsatn::to_vec(&erase_margin_cell_reducer::EraseMarginCellArgs {
                    q: q.clone(),
                    r: r.clone(),
                })
            }
            Reducer::LikeIsland { island_id } => {
                __sats::bsatn::to_vec(&like_island_reducer::LikeIslandArgs {
                    island_id: island_id.clone(),
                })
            }
            Reducer::MergeWithCell { cell_kind, cell_id } => {
                __sats::bsatn::to_vec(&merge_with_cell_reducer::MergeWithCellArgs {
                    cell_kind: cell_kind.clone(),
                    cell_id: cell_id.clone(),
                })
            }
            Reducer::PaintCommunityCell { q_local, r_local } => {
                __sats::bsatn::to_vec(&paint_community_cell_reducer::PaintCommunityCellArgs {
                    q_local: q_local.clone(),
                    r_local: r_local.clone(),
                })
            }
            Reducer::PaintIslandCell { q_local, r_local } => {
                __sats::bsatn::to_vec(&paint_island_cell_reducer::PaintIslandCellArgs {
                    q_local: q_local.clone(),
                    r_local: r_local.clone(),
                })
            }
            Reducer::PaintMarginCell { q, r } => {
                __sats::bsatn::to_vec(&paint_margin_cell_reducer::PaintMarginCellArgs {
                    q: q.clone(),
                    r: r.clone(),
                })
            }
            Reducer::ResetAccount => {
                __sats::bsatn::to_vec(&reset_account_reducer::ResetAccountArgs {})
            }
            Reducer::SetBrush { hue, sat, val } => {
                __sats::bsatn::to_vec(&set_brush_reducer::SetBrushArgs {
                    hue: hue.clone(),
                    sat: sat.clone(),
                    val: val.clone(),
                })
            }
            Reducer::SetFrozen { frozen } => {
                __sats::bsatn::to_vec(&set_frozen_reducer::SetFrozenArgs {
                    frozen: frozen.clone(),
                })
            }
            Reducer::SetIslandBorder => {
                __sats::bsatn::to_vec(&set_island_border_reducer::SetIslandBorderArgs {})
            }
            Reducer::SetIslandLink { rate_id } => {
                __sats::bsatn::to_vec(&set_island_link_reducer::SetIslandLinkArgs {
                    rate_id: rate_id.clone(),
                })
            }
            Reducer::SetLock { locked } => __sats::bsatn::to_vec(&set_lock_reducer::SetLockArgs {
                locked: locked.clone(),
            }),
            Reducer::SetName { name } => {
                __sats::bsatn::to_vec(&set_name_reducer::SetNameArgs { name: name.clone() })
            }
            Reducer::SetPos { cx, cy } => __sats::bsatn::to_vec(&set_pos_reducer::SetPosArgs {
                cx: cx.clone(),
                cy: cy.clone(),
            }),
            Reducer::ShowIslandBorder => {
                __sats::bsatn::to_vec(&show_island_border_reducer::ShowIslandBorderArgs {})
            }
            Reducer::UnlikeIsland { island_id } => {
                __sats::bsatn::to_vec(&unlike_island_reducer::UnlikeIslandArgs {
                    island_id: island_id.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    config: __sdk::TableUpdate<Config>,
    gift: __sdk::TableUpdate<Gift>,
    hexa_cluster: __sdk::TableUpdate<HexaCluster>,
    hexa_event: __sdk::TableUpdate<HexaEvent>,
    inventory: __sdk::TableUpdate<Inventory>,
    island: __sdk::TableUpdate<Island>,
    island_cell: __sdk::TableUpdate<IslandCell>,
    island_like: __sdk::TableUpdate<IslandLike>,
    island_link_click: __sdk::TableUpdate<IslandLinkClick>,
    margin_cell: __sdk::TableUpdate<MarginCell>,
    user: __sdk::TableUpdate<User>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "config" => db_update
                    .config
                    .append(config_table::parse_table_update(table_update)?),
                "gift" => db_update
                    .gift
                    .append(gift_table::parse_table_update(table_update)?),
                "hexa_cluster" => db_update
                    .hexa_cluster
                    .append(hexa_cluster_table::parse_table_update(table_update)?),
                "hexa_event" => db_update
                    .hexa_event
                    .append(hexa_event_table::parse_table_update(table_update)?),
                "inventory" => db_update
                    .inventory
                    .append(inventory_table::parse_table_update(table_update)?),
                "island" => db_update
                    .island
                    .append(island_table::parse_table_update(table_update)?),
                "island_cell" => db_update
                    .island_cell
                    .append(island_cell_table::parse_table_update(table_update)?),
                "island_like" => db_update
                    .island_like
                    .append(island_like_table::parse_table_update(table_update)?),
                "island_link_click" => db_update
                    .island_link_click
                    .append(island_link_click_table::parse_table_update(table_update)?),
                "margin_cell" => db_update
                    .margin_cell
                    .append(margin_cell_table::parse_table_update(table_update)?),
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.config = cache
            .apply_diff_to_table::<Config>("config", &self.config)
            .with_updates_by_pk(|row| &row.id);
        diff.gift = cache
            .apply_diff_to_table::<Gift>("gift", &self.gift)
            .with_updates_by_pk(|row| &row.id);
        diff.hexa_cluster = cache
            .apply_diff_to_table::<HexaCluster>("hexa_cluster", &self.hexa_cluster)
            .with_updates_by_pk(|row| &row.identity);
        diff.hexa_event = cache
            .apply_diff_to_table::<HexaEvent>("hexa_event", &self.hexa_event)
            .with_updates_by_pk(|row| &row.id);
        diff.inventory = cache
            .apply_diff_to_table::<Inventory>("inventory", &self.inventory)
            .with_updates_by_pk(|row| &row.id);
        diff.island = cache
            .apply_diff_to_table::<Island>("island", &self.island)
            .with_updates_by_pk(|row| &row.id);
        diff.island_cell = cache
            .apply_diff_to_table::<IslandCell>("island_cell", &self.island_cell)
            .with_updates_by_pk(|row| &row.id);
        diff.island_like = cache
            .apply_diff_to_table::<IslandLike>("island_like", &self.island_like)
            .with_updates_by_pk(|row| &row.id);
        diff.island_link_click = cache
            .apply_diff_to_table::<IslandLinkClick>("island_link_click", &self.island_link_click)
            .with_updates_by_pk(|row| &row.id);
        diff.margin_cell = cache
            .apply_diff_to_table::<MarginCell>("margin_cell", &self.margin_cell)
            .with_updates_by_pk(|row| &row.id);
        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.identity);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "config" => db_update
                    .config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "gift" => db_update
                    .gift
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hexa_cluster" => db_update
                    .hexa_cluster
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "hexa_event" => db_update
                    .hexa_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "island" => db_update
                    .island
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "island_cell" => db_update
                    .island_cell
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "island_like" => db_update
                    .island_like
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "island_link_click" => db_update
                    .island_link_click
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "margin_cell" => db_update
                    .margin_cell
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "config" => db_update
                    .config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "gift" => db_update
                    .gift
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hexa_cluster" => db_update
                    .hexa_cluster
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "hexa_event" => db_update
                    .hexa_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "inventory" => db_update
                    .inventory
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "island" => db_update
                    .island
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "island_cell" => db_update
                    .island_cell
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "island_like" => db_update
                    .island_like
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "island_link_click" => db_update
                    .island_link_click
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "margin_cell" => db_update
                    .margin_cell
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    config: __sdk::TableAppliedDiff<'r, Config>,
    gift: __sdk::TableAppliedDiff<'r, Gift>,
    hexa_cluster: __sdk::TableAppliedDiff<'r, HexaCluster>,
    hexa_event: __sdk::TableAppliedDiff<'r, HexaEvent>,
    inventory: __sdk::TableAppliedDiff<'r, Inventory>,
    island: __sdk::TableAppliedDiff<'r, Island>,
    island_cell: __sdk::TableAppliedDiff<'r, IslandCell>,
    island_like: __sdk::TableAppliedDiff<'r, IslandLike>,
    island_link_click: __sdk::TableAppliedDiff<'r, IslandLinkClick>,
    margin_cell: __sdk::TableAppliedDiff<'r, MarginCell>,
    user: __sdk::TableAppliedDiff<'r, User>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Config>("config", &self.config, event);
        callbacks.invoke_table_row_callbacks::<Gift>("gift", &self.gift, event);
        callbacks.invoke_table_row_callbacks::<HexaCluster>(
            "hexa_cluster",
            &self.hexa_cluster,
            event,
        );
        callbacks.invoke_table_row_callbacks::<HexaEvent>("hexa_event", &self.hexa_event, event);
        callbacks.invoke_table_row_callbacks::<Inventory>("inventory", &self.inventory, event);
        callbacks.invoke_table_row_callbacks::<Island>("island", &self.island, event);
        callbacks.invoke_table_row_callbacks::<IslandCell>("island_cell", &self.island_cell, event);
        callbacks.invoke_table_row_callbacks::<IslandLike>("island_like", &self.island_like, event);
        callbacks.invoke_table_row_callbacks::<IslandLinkClick>(
            "island_link_click",
            &self.island_link_click,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MarginCell>("margin_cell", &self.margin_cell, event);
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        config_table::register_table(client_cache);
        gift_table::register_table(client_cache);
        hexa_cluster_table::register_table(client_cache);
        hexa_event_table::register_table(client_cache);
        inventory_table::register_table(client_cache);
        island_table::register_table(client_cache);
        island_cell_table::register_table(client_cache);
        island_like_table::register_table(client_cache);
        island_link_click_table::register_table(client_cache);
        margin_cell_table::register_table(client_cache);
        user_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "config",
        "gift",
        "hexa_cluster",
        "hexa_event",
        "inventory",
        "island",
        "island_cell",
        "island_like",
        "island_link_click",
        "margin_cell",
        "user",
    ];
}
