// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PaintCommunityCellArgs {
    pub q_local: i32,
    pub r_local: i32,
}

impl From<PaintCommunityCellArgs> for super::Reducer {
    fn from(args: PaintCommunityCellArgs) -> Self {
        Self::PaintCommunityCell {
            q_local: args.q_local,
            r_local: args.r_local,
        }
    }
}

impl __sdk::InModule for PaintCommunityCellArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `paint_community_cell`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait paint_community_cell {
    /// Request that the remote module invoke the reducer `paint_community_cell` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`paint_community_cell:paint_community_cell_then`] to run a callback after the reducer completes.
    fn paint_community_cell(&self, q_local: i32, r_local: i32) -> __sdk::Result<()> {
        self.paint_community_cell_then(q_local, r_local, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `paint_community_cell` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn paint_community_cell_then(
        &self,
        q_local: i32,
        r_local: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl paint_community_cell for super::RemoteReducers {
    fn paint_community_cell_then(
        &self,
        q_local: i32,
        r_local: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PaintCommunityCellArgs { q_local, r_local }, callback)
    }
}
