// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ReapSchedule {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for ReapSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ReapSchedule`.
///
/// Provides typed access to columns for query building.
pub struct ReapScheduleCols {
    pub scheduled_id: __sdk::__query_builder::Col<ReapSchedule, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<ReapSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for ReapSchedule {
    type Cols = ReapScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReapScheduleCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ReapSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReapScheduleIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<ReapSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for ReapSchedule {
    type IxCols = ReapScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReapScheduleIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ReapSchedule {}
