// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RerankWarnSchedule {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for RerankWarnSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RerankWarnSchedule`.
///
/// Provides typed access to columns for query building.
pub struct RerankWarnScheduleCols {
    pub scheduled_id: __sdk::__query_builder::Col<RerankWarnSchedule, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<RerankWarnSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for RerankWarnSchedule {
    type Cols = RerankWarnScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RerankWarnScheduleCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RerankWarnSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct RerankWarnScheduleIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<RerankWarnSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for RerankWarnSchedule {
    type IxCols = RerankWarnScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RerankWarnScheduleIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RerankWarnSchedule {}
