// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetFrozenArgs {
    pub frozen: bool,
}

impl From<SetFrozenArgs> for super::Reducer {
    fn from(args: SetFrozenArgs) -> Self {
        Self::SetFrozen {
            frozen: args.frozen,
        }
    }
}

impl __sdk::InModule for SetFrozenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_frozen`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_frozen {
    /// Request that the remote module invoke the reducer `set_frozen` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_frozen:set_frozen_then`] to run a callback after the reducer completes.
    fn set_frozen(&self, frozen: bool) -> __sdk::Result<()> {
        self.set_frozen_then(frozen, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_frozen` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_frozen_then(
        &self,
        frozen: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_frozen for super::RemoteReducers {
    fn set_frozen_then(
        &self,
        frozen: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetFrozenArgs { frozen }, callback)
    }
}
