// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnlikeIslandArgs {
    pub island_id: u32,
}

impl From<UnlikeIslandArgs> for super::Reducer {
    fn from(args: UnlikeIslandArgs) -> Self {
        Self::UnlikeIsland {
            island_id: args.island_id,
        }
    }
}

impl __sdk::InModule for UnlikeIslandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unlike_island`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unlike_island {
    /// Request that the remote module invoke the reducer `unlike_island` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unlike_island:unlike_island_then`] to run a callback after the reducer completes.
    fn unlike_island(&self, island_id: u32) -> __sdk::Result<()> {
        self.unlike_island_then(island_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unlike_island` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unlike_island_then(
        &self,
        island_id: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl unlike_island for super::RemoteReducers {
    fn unlike_island_then(
        &self,
        island_id: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UnlikeIslandArgs { island_id }, callback)
    }
}
