// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct User {
    pub identity: __sdk::Identity,
    pub name: Option<String>,
    pub online: bool,
    pub cx: f32,
    pub cy: f32,
    pub last_seen: __sdk::Timestamp,
    pub hue: u16,
    pub sat: u8,
    pub val: u8,
    pub locked: bool,
    pub xp: u64,
    pub paint_tokens: f32,
    pub tokens_at: __sdk::Timestamp,
}

impl __sdk::InModule for User {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `User`.
///
/// Provides typed access to columns for query building.
pub struct UserCols {
    pub identity: __sdk::__query_builder::Col<User, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<User, Option<String>>,
    pub online: __sdk::__query_builder::Col<User, bool>,
    pub cx: __sdk::__query_builder::Col<User, f32>,
    pub cy: __sdk::__query_builder::Col<User, f32>,
    pub last_seen: __sdk::__query_builder::Col<User, __sdk::Timestamp>,
    pub hue: __sdk::__query_builder::Col<User, u16>,
    pub sat: __sdk::__query_builder::Col<User, u8>,
    pub val: __sdk::__query_builder::Col<User, u8>,
    pub locked: __sdk::__query_builder::Col<User, bool>,
    pub xp: __sdk::__query_builder::Col<User, u64>,
    pub paint_tokens: __sdk::__query_builder::Col<User, f32>,
    pub tokens_at: __sdk::__query_builder::Col<User, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for User {
    type Cols = UserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            online: __sdk::__query_builder::Col::new(table_name, "online"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cy: __sdk::__query_builder::Col::new(table_name, "cy"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
            hue: __sdk::__query_builder::Col::new(table_name, "hue"),
            sat: __sdk::__query_builder::Col::new(table_name, "sat"),
            val: __sdk::__query_builder::Col::new(table_name, "val"),
            locked: __sdk::__query_builder::Col::new(table_name, "locked"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
            paint_tokens: __sdk::__query_builder::Col::new(table_name, "paint_tokens"),
            tokens_at: __sdk::__query_builder::Col::new(table_name, "tokens_at"),
        }
    }
}

/// Indexed column accessor struct for the table `User`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserIxCols {
    pub identity: __sdk::__query_builder::IxCol<User, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for User {
    type IxCols = UserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for User {}
